# Generated by Django 4.0.5 on 2023-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('service', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
