# Generated by Django 4.0.5 on 2023-03-01 11:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='blog_images')),
                ('title', models.CharField(max_length=180)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('publish_date', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
