# Generated by Django 4.0.5 on 2023-03-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
    ]
