# Generated by Django 4.0.5 on 2023-03-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_description_blog_main_image_blog_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='other_description',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
