# Generated by Django 4.0.5 on 2023-03-01 12:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='other_description',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='abc'),
            preserve_default=False,
        ),
    ]
