# Generated by Django 4.0.5 on 2023-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='about_us_image')),
                ('discriptiom', models.TextField()),
                ('button_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AreasCovered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name_one', models.TextField()),
                ('area_name_two', models.TextField()),
                ('area_name_three', models.TextField()),
                ('area_name_four', models.TextField()),
                ('area_name_five', models.TextField()),
                ('area_name_six', models.TextField()),
                ('area_name_seven', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('email', models.TextField()),
                ('mobile', models.CharField(max_length=20)),
                ('services', models.TextField()),
                ('property', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('discriptiom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='footer_image')),
                ('discriptiom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GenralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('insta_url', models.TextField()),
                ('facbook_url', models.TextField()),
                ('twitter_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('background_image', models.ImageField(upload_to='header_image')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_image')),
                ('order_no', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='why_choose_property_image')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='why_choose_us_image')),
                ('discriptiom', models.TextField()),
            ],
        ),
    ]
