# Generated by Django 4.0.5 on 2023-02-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='discriptiom',
            new_name='discription',
        ),
    ]
