# Generated by Django 4.0.5 on 2023-02-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0002_rename_discriptiom_footer_discription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name_plural': 'Header'},
        ),
    ]
