# Generated by Django 4.0.5 on 2023-02-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0003_alter_header_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePropertyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_management_assessment_One', models.TextField(max_length=120)),
                ('property_management_assessment_Two', models.TextField(max_length=120)),
                ('property_management_assessment_Three', models.TextField(max_length=120)),
                ('property_management_assessment_Four', models.TextField(max_length=120)),
                ('property_management_assessment_Five', models.TextField(max_length=120)),
                ('property_management_assessment_description_one', models.TextField()),
                ('property_management_assessment_description_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeImpromentsContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('email', models.TextField()),
                ('mobile', models.CharField(max_length=20)),
                ('services', models.TextField()),
                ('property_type', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(max_length=128)),
                ('vision', models.TextField(max_length=128)),
                ('discriptiom', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurPropertyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_one', models.TextField(max_length=60)),
                ('services_two', models.TextField(max_length=60)),
                ('services_three', models.TextField(max_length=60)),
                ('services_four', models.TextField(max_length=60)),
                ('services_five', models.TextField(max_length=60)),
                ('services_six', models.TextField(max_length=60)),
                ('services_seven', models.TextField(max_length=60)),
                ('services_eight', models.TextField(max_length=60)),
                ('image', models.ImageField(upload_to='property_image')),
            ],
        ),
        migrations.CreateModel(
            name='OurPropertyManagementServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription_one', models.TextField()),
                ('discription_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('discription', models.TextField()),
                ('our_services_main_description_one', models.TextField()),
                ('our_services_main_description_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('email', models.TextField()),
                ('mobile', models.CharField(max_length=20)),
                ('services', models.TextField()),
                ('property_type', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyHomeImprovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_renovations_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='testimonials_image')),
                ('name', models.CharField(max_length=40)),
                ('image_two', models.ImageField(upload_to='testimonials_image')),
                ('image_three', models.ImageField(upload_to='testimonials_image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='discriptiom',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='property',
            new_name='property_type',
        ),
    ]
