# Generated by Django 4.0.5 on 2023-02-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0004_freepropertymanagement_homeimpromentscontactus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourmissionvision',
            old_name='discriptiom',
            new_name='discription',
        ),
    ]
