# Generated by Django 4.0.5 on 2023-03-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='about_us_image')),
                ('description', models.TextField()),
                ('button_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AreasCovered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'AreasCovered',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('services', models.TextField()),
                ('property_type', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FreePropertyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_management_assessment_One', models.TextField(max_length=120)),
                ('property_management_assessment_Two', models.TextField(max_length=120)),
                ('property_management_assessment_Three', models.TextField(max_length=120)),
                ('property_management_assessment_Four', models.TextField(max_length=120)),
                ('property_management_assessment_Five', models.TextField(max_length=120)),
                ('property_management_assessment_description_one', models.TextField()),
                ('property_management_assessment_description_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField()),
                ('email', models.TextField()),
                ('insta_url', models.TextField()),
                ('facbook_url', models.TextField()),
                ('twitter_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('background_image', models.ImageField(upload_to='header_image')),
            ],
            options={
                'verbose_name_plural': 'Headerssss',
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_image')),
                ('order_no', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'HeroSlider',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='OurMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurPropertyManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_one', models.TextField(max_length=60)),
                ('services_two', models.TextField(max_length=60)),
                ('services_three', models.TextField(max_length=60)),
                ('services_four', models.TextField(max_length=60)),
                ('services_five', models.TextField(max_length=60)),
                ('services_six', models.TextField(max_length=60)),
                ('services_seven', models.TextField(max_length=60)),
                ('services_eight', models.TextField(max_length=60)),
                ('image', models.ImageField(upload_to='property_image')),
            ],
        ),
        migrations.CreateModel(
            name='OurPropertyManagementServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_one', models.TextField()),
                ('description_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurServicesdescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_services_main_description_one', models.TextField()),
                ('our_services_main_description_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyHomeImprovements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_renovations_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.BigIntegerField(unique=True)),
                ('rental_image_one', models.ImageField(upload_to='rental_images')),
                ('rental_image_two', models.ImageField(upload_to='rental_images')),
                ('rental_image_three', models.ImageField(upload_to='rental_images')),
                ('rental_image_four', models.ImageField(upload_to='rental_images')),
                ('rental_image_five', models.ImageField(upload_to='rental_images')),
                ('price', models.IntegerField()),
                ('address', models.TextField()),
                ('bedroom', models.SmallIntegerField()),
                ('bathroom', models.SmallIntegerField()),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
                ('ownership_type', models.CharField(max_length=120)),
                ('property_description', models.TextField()),
                ('property_types', models.CharField(choices=[('1', 'Appartment'), ('2', 'Condo'), ('3', 'Du/Fourplex'), ('4', 'House'), ('5', 'Hometown'), ('6', 'commercial')], default='4', max_length=2)),
                ('is_pet_friendly', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to='testimonials_image')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order_no', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='WhyChoosePropertyManagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='why_choose_property_image')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('image', models.ImageField(upload_to='why_choose_us_image')),
                ('description', models.TextField()),
            ],
        ),
    ]
