# Generated by Django 4.0.5 on 2023-03-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
