# Generated by Django 4.0.5 on 2023-03-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_management', '0002_contactus_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='listing_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
